name: Publish Production Helm Charts
on:
  push:
    tags:
      - '*'

jobs:
  call-workflow-passing-data:
    uses: GlueOps/github-workflows/.github/workflows/publish-metacontroller-helm-chart.yml@v20230403
    secrets: inherit
    with:
      VERSION_TAG: "v4.10.0"
      GLUEOPS_ENV: "production"
      HELM_CHART_REPO_NAME: "platform"
